export const SET_ERROR = "SET_ERROR";

export const SET_CURRENT_ENTITY = "SET_CURRENT_ENTITY";
export const SET_MENU_TREE_VISIBLE = "SET_MENU_TREE_VISIBLE";

export const SET_STATES = "SET_STATES";
export const SET_DISTRICTS_BY_STATE = "SET_DISTRICTS_BY_STATE";
export const SET_BBOXES = "SET_BBOXES";

export const SET_LEGISLATORS = "SET_LEGISLATORS";
export const SET_LEGISLATORS_BY_STATE = "SET_LEGISLATORS_BY_STATE";
